# frozen_string_literal: true

require "rails_helper"

RSpec.describe Pito::Themes::CssGenerator do
  subject(:css) { described_class.call }

  it "starts with the generated-file header" do
    expect(css).to start_with("/* GENERATED by rake pito:themes:export — do not edit */")
  end

  it "includes a :root block" do
    expect(css).to include(":root {")
  end

  describe "tokyo-night block" do
    it "includes the [data-theme] selector" do
      expect(css).to include('[data-theme="tokyo-night"]')
    end

    it "sets --bg-root to the correct value" do
      expect(css).to include("--bg-root: #1a1b26;")
    end

    it "sets --fg-default to the correct value" do
      expect(css).to include("--fg-default: #c0caf5;")
    end

    it "sets --brand-pito to the correct value" do
      expect(css).to include("--brand-pito: #5170ff;")
    end
  end

  describe "dracula block" do
    it "includes the [data-theme] selector" do
      expect(css).to include('[data-theme="dracula"]')
    end
  end

  it "includes a [data-theme] block for every registered slug" do
    Pito::Themes::Registry.all.each do |defn|
      expect(css).to include("[data-theme=\"#{defn.slug}\"]")
    end
  end

  it "includes --brand-pito: #5170ff in every theme block" do
    Pito::Themes::Registry.all.each do |defn|
      # Each block must declare --brand-pito; the constant value is always #5170ff
      expect(defn.tokens[:brand_pito]).to eq("#5170ff")
    end
    # And the generated CSS contains the value at least once per theme
    occurrences = css.scan("--brand-pito: #5170ff;").length
    expect(occurrences).to be >= Pito::Themes::Registry.all.length
  end

  it "includes --brand-pito: #5170ff in :root" do
    # :root mirrors the default theme tokens
    root_block = css[/:root \{[^}]+\}/m]
    expect(root_block).to include("--brand-pito: #5170ff;")
  end
end
