# 2026-05-20 — Export the canonical Ruby-source-of-truth theme to the
# two consumer artifacts:
#
#   - `app/assets/tailwind/_theme.css` — imported from
#     `app/assets/tailwind/application.css` via `@import "_theme.css";`.
#   - `extras/cli/src/theme.rs` — consumed by the future Ratatui CLI.
#
# The task is idempotent: re-running it produces byte-identical output
# whenever `Pito::Theme` hasn't changed.
#
# Safety guard for the Rust target: the file at `extras/cli/src/theme.rs`
# is owned by the `cli-impl` agent and may already contain a hand-curated
# typed-Color wrapper. To avoid clobbering that file from a different
# agent's lane, the rake task only writes the Rust artifact when:
#
#   1. The file does not yet exist, OR
#   2. The existing file starts with the auto-generated header line
#      (i.e. an earlier `pito:theme:export` invocation produced it).
#
# If a hand-written `theme.rs` is detected, the task prints a SKIP
# notice listing the destination path so a follow-up cli-impl dispatch
# can refactor the file to consume the generated atoms.
namespace :pito do
  namespace :theme do
    desc "Export the pito theme to CSS + Rust artifacts"
    task export: :environment do
      css_path  = Rails.root.join("app/assets/tailwind/_theme.css")
      rust_path = Rails.root.join("extras/cli/src/theme.rs")
      rust_header = "// Auto-generated by `rake pito:theme:export`."

      css_path.write(Pito::Theme.export_css)
      puts "Wrote #{css_path}"

      if rust_path.parent.exist?
        existing = rust_path.exist? ? rust_path.read : nil
        if existing.nil? || existing.start_with?(rust_header)
          rust_path.write(Pito::Theme.export_rust)
          puts "Wrote #{rust_path}"
        else
          puts "Skipped #{rust_path} (hand-written file detected — " \
               "dispatch cli-impl to refactor it to consume the " \
               "generated atoms before re-running this task)."
        end
      else
        puts "Skipped #{rust_path} (extras/cli/src/ doesn't exist yet)"
      end
    end
  end
end
