# frozen_string_literal: true

require "rails_helper"
require "tmpdir"

# Tests that CssGenerator.call produces the content written by
# `pito:themes:export`, and that the output is a non-empty, valid CSS file
# starting with the generated header.
RSpec.describe "pito:themes:export (generator writes file)" do
  let(:output_path) { Pathname.new(Dir.mktmpdir).join("themes.css") }
  let(:css) { Pito::Themes::CssGenerator.call }

  before do
    File.write(output_path, css)
  end

  after do
    FileUtils.rm_rf(output_path.dirname)
  end

  it "writes a non-empty file" do
    expect(output_path.size).to be > 0
  end

  it "starts with the generated header" do
    first_line = output_path.readlines.first
    expect(first_line).to start_with("/* GENERATED by rake pito:themes:export — do not edit */")
  end

  it "contains :root and at least one [data-theme] block" do
    content = output_path.read
    expect(content).to include(":root {")
    expect(content).to match(/\[data-theme="[^"]+"\]/)
  end

  it "is not empty after round-trip through the file system" do
    content = output_path.read
    expect(content).not_to be_empty
  end
end
