require "rails_helper"
require "rake"

# Spec for `lib/tasks/pito_theme.rake`. The `pito:theme:export` task is
# the bridge between the Ruby `Pito::Theme` source of truth and its two
# generated artifacts: `app/assets/tailwind/_theme.css` and
# `extras/cli/src/theme.rs`. These specs assert that the task writes the
# expected content, is idempotent, and honors the safety guard that
# prevents clobbering a hand-written Rust theme file in the cli-impl
# agent's lane.
RSpec.describe "pito:theme:export rake task" do
  before(:all) do
    Rake.application.rake_require(
      "tasks/pito_theme",
      [ Rails.root.join("lib").to_s ],
      []
    )
    Rake::Task.define_task(:environment)
  end

  let(:task) { Rake::Task["pito:theme:export"] }

  let(:css_path) { Rails.root.join("app/assets/tailwind/_theme.css") }
  let(:rust_path) { Rails.root.join("extras/cli/src/theme.rs") }

  let(:rust_header) { "// Auto-generated by `rake pito:theme:export`." }

  # Snapshot original files so the spec is non-destructive: anything we
  # overwrote/created during the example is restored in `after`.
  let(:css_original) { css_path.exist? ? css_path.read : nil }
  let(:rust_original) { rust_path.exist? ? rust_path.read : nil }

  before do
    css_original
    rust_original
    task.reenable
  end

  after do
    if css_original.nil?
      css_path.delete if css_path.exist?
    else
      css_path.write(css_original)
    end

    if rust_original.nil?
      rust_path.delete if rust_path.exist?
    else
      rust_path.write(rust_original)
    end
  end

  describe "CSS artifact" do
    it "writes app/assets/tailwind/_theme.css with valid theme content" do
      capture_stdout { task.invoke }

      expect(css_path).to exist
      content = css_path.read

      expect(content).to start_with(":root {\n")
      expect(content).to include("--dracula-bg: #282a36;")
      expect(content).to include("--section-accent-settings: #ffb86c;")
      expect(content).to include("--bg-section-settings: #34333b;")
      expect(content).to include("--color-danger: #ff79c6;")
    end

    it "writes exactly the content returned by Pito::Theme.export_css" do
      capture_stdout { task.invoke }

      expect(css_path.read).to eq(Pito::Theme.export_css)
    end

    it "is idempotent — two consecutive invocations leave the same byte content on disk" do
      capture_stdout { task.invoke }
      first = css_path.read

      task.reenable
      capture_stdout { task.invoke }
      second = css_path.read

      expect(second).to eq(first)
    end
  end

  describe "Rust artifact" do
    context "when extras/cli/src/ exists and the existing theme.rs starts with the auto-generated header" do
      before do
        # Pre-seed an auto-generated artifact so the safety guard allows
        # the rake task to overwrite it.
        rust_path.write("#{rust_header}\n// stub\n")
      end

      it "writes the Pito::Theme.export_rust output verbatim" do
        capture_stdout { task.invoke }

        expect(rust_path.read).to eq(Pito::Theme.export_rust)
      end

      it "is idempotent across two invocations" do
        capture_stdout { task.invoke }
        first = rust_path.read

        task.reenable
        capture_stdout { task.invoke }
        second = rust_path.read

        expect(second).to eq(first)
      end
    end

    context "when extras/cli/src/theme.rs exists but is hand-written (no auto-generated header)" do
      before do
        rust_path.write("// Hand-curated Ratatui theme — do not auto-overwrite.\n")
      end

      it "leaves the file untouched and prints a SKIP notice" do
        out = capture_stdout { task.invoke }

        expect(rust_path.read).to start_with("// Hand-curated Ratatui theme")
        expect(out).to include("Skipped")
        expect(out).to include("theme.rs")
      end
    end

    context "when extras/cli/src/theme.rs does not yet exist" do
      before { rust_path.delete if rust_path.exist? }

      it "writes a fresh file with the auto-generated content" do
        capture_stdout { task.invoke }

        expect(rust_path).to exist
        expect(rust_path.read).to eq(Pito::Theme.export_rust)
      end
    end
  end

  describe "stdout" do
    before do
      # Force the auto-generated path so we get a "Wrote ..." line for
      # the Rust artifact.
      rust_path.write("#{rust_header}\n")
    end

    it "prints a `Wrote ...` line for both artifacts" do
      out = capture_stdout { task.invoke }

      expect(out).to include("Wrote #{css_path}")
      expect(out).to include("Wrote #{rust_path}")
    end
  end

  def capture_stdout
    original = $stdout
    $stdout = StringIO.new
    yield
    $stdout.string
  ensure
    $stdout = original
  end
end
