# Pin vendored modules
pin "@xterm/xterm", to: "xterm.js"
pin "@xterm/addon-fit", to: "addon-fit.js"
pin "@xterm/addon-web-links", to: "addon-web-links.js"
pin "@rails/actioncable", to: "actioncable.js"
pin "application", to: "application.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
