# Pin vendored modules
pin "@xterm/xterm", to: "xterm.js"
pin "@hotwired/turbo-rails", to: "turbo.min.js", preload: true
pin "@rails/actioncable", to: "actioncable.js"
pin "application", to: "application.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "pito/auth", to: "pito/auth.js"
pin "pito/settings", to: "pito/settings.js"
pin "pito/turbo_actions", to: "pito/turbo_actions.js"
pin "pito/ready", to: "pito/ready.js"
pin "pito/reveal_queue", to: "pito/reveal_queue.js"
pin "pito/reveal_engine", to: "pito/reveal_engine.js"
pin "pito/typing", to: "pito/typing.js"
pin "pito/diff", to: "pito/diff.js"
