// >>> TRANSITIONS_TOKENS auto-generated by rake pito:transitions:export — DO NOT EDIT <<<
// Pito::Transitions::Tokens parity for the Ratatui TUI.
//
// 2 transitions (scramble-settle + color-crossfade) + 1 decoration (shimmer).
// All values mirror app/services/pito/transitions/tokens.rb.

pub const SCRAMBLE_DURATION_MS: u32 = 200;
pub const SCRAMBLE_STAGGER_MS: u32 = 30;
pub const SCRAMBLE_FRAME_MS: u32 = 30;
pub const COLOR_CROSSFADE_DURATION_MS: u32 = 300;
pub const COLOR_CROSSFADE_EASING: &'static str = "ease-out";
pub const SHIMMER_CYCLE_MS: u32 = 1600;
pub const SHIMMER_GRADIENT_STOPS: &'static str = "muted 0%, muted 40%, accent 50%, muted 60%, muted 100%";
pub const DEBOUNCE_MS: u32 = 80;

