require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Use Redis for caching in development
  config.cache_store = :redis_cache_store, { url: ENV.fetch("REDIS_URL", "redis://127.0.0.1:64527/0") }

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Use the public Cloudflare-tunneled host for links generated in mailer
  # templates and any URL helpers that need an absolute URL. The same canonical
  # host is also wired into Rails.application.routes.default_url_options below.
  config.action_mailer.default_url_options = { host: "app.pitomd.com", protocol: "https" }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # ActionCable allowed origins. Browsers connect via the public Cloudflare
  # tunnel, so we must accept https://app.pitomd.com and https://mcp.pitomd.com
  # in addition to the local-development default of localhost / 127.0.0.1.
  config.action_cable.allowed_request_origins = [
    "https://app.pitomd.com",
    "https://mcp.pitomd.com",
    %r{https?://localhost(:\d+)?},
    %r{https?://127\.0\.0\.1(:\d+)?}
  ]

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Allow Cloudflare Tunnel hostnames. Rails 6+ rejects requests with unknown
  # Host headers in development; the pito CLI and any browser hitting the tunnel
  # arrive here with Host: app.pitomd.com (or mcp.pitomd.com). "localhost",
  # "127.0.0.1", and "::1" are already in config.hosts by default.
  config.hosts << "app.pitomd.com"
  config.hosts << "mcp.pitomd.com"

  # Default URL options for url_for, redirect_to(host:), and any *_url helper
  # called outside a request context (mailers, jobs, console). The Cloudflare
  # tunnel terminates TLS, so external URLs are always https.
  Rails.application.routes.default_url_options = { host: "app.pitomd.com", protocol: "https" }

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!

  # Phase 10 — MCP scope simplification (ADR 0004). Expose the `dev`
  # scope in development so the dev-KB MCP tools (`list_docs`, `read_doc`,
  # `save_note`) are registered and reachable.
  config.x.mcp.expose_dev_scope = true

  # Phase 25 — 01d. Expose the `auth` scope in development so the
  # login-security MCP tools (`login_attempts_pending`, `login_attempts_list`,
  # `login_attempt_approve`, `login_attempt_block`, `login_attempt_unblock`,
  # `login_attempt_purge`, `auth_audit_log_list`) are registered and
  # reachable. Strips on release per ADR 0004 precedent.
  config.x.mcp.expose_auth_scope = true
end
