require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Use SolidCache (Postgres-backed) — reads config/cache.yml
  config.cache_store = :solid_cache_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :development

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Dev runs jobs on an in-process thread pool (no SolidQueue tables / worker
  # process needed locally — mirrors the async cable adapter). Production keeps
  # SolidQueue (config.active_job.queue_adapter = :solid_queue in application.rb).
  # To exercise SolidQueue locally instead: load db/queue_schema.rb and run with
  # SOLID_QUEUE_IN_PUMA=1 (see config/puma.rb).
  config.active_job.queue_adapter = :async

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Action Cable allowed request origins
  config.action_cable.allowed_request_origins = [
    %r{https?://localhost(:\d+)?},
    %r{https?://127\.0\.0\.1(:\d+)?},
    %r{.*}  # accept any origin for development
  ]

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # No extra allowed hosts needed in dev: "localhost", "127.0.0.1", and "::1"
  # are already permitted by Rails by default.

  # Default URL options for url_for, redirect_to(host:), and any *_url helper
  # called outside a request context (mailers, jobs, console). Dev runs plain
  # http on localhost:3027.
  Rails.application.routes.default_url_options = { host: "localhost", port: 3027 }

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
