# frozen_string_literal: true

require "rails_helper"

# ── Dispatch matrix: `farewell` (recognition only, zero DB) ───────────────────
#
# Farewells are NL-detected — phrase-matched against the WHOLE normalized input
# in Pito::Chat::Parser BEFORE any verb tokenisation.  The grammar spec for
# :farewell exists only for handler↔spec parity; recognition does NOT go through
# the grammar registry.
#
# Entry point:
#   Pito::Chat::Parser.call(tokens, raw:, conversation:)
#
# Normalizer (normalized_phrase, private):
#   @raw.to_s.strip.downcase.gsub(/[[:punct:]]+\z/, "").strip.gsub(/\s+/, " ")
#
# Match set:
#   Pito::Chat::Parser::FAREWELLS — frozen Set, 29 canonical lower-case phrases
#
# DB access: NONE on the farewell code path (short-circuits before the grammar
# registry or any ActiveRecord call).  No factories, no mocking required.
#
# RULE: every phrase in FAREWELLS is recognized — no exception.
RSpec.describe "Dispatch matrix — farewell (recognition, zero DB)", type: :dispatch do
  # Parse raw input through the real parser.
  # `conversation:` is passed but never read on the farewell path.
  # Tokens are generated by the real (pure) lexer — the farewell path uses
  # @raw, not @tokens, so the token array content doesn't affect the result.
  def parse(raw)
    tokens = Pito::Lex::Lexer.call(raw)
    Pito::Chat::Parser.call(tokens, raw: raw, conversation: double("conversation"))
  end

  def farewell?(raw)
    parse(raw).tool == :farewell
  end

  # ── 1. Canonical forms — every entry in FAREWELLS, unmodified ───────────────
  #
  # Exercises the set membership directly: if a phrase is added to or removed
  # from FAREWELLS the test count changes and CI catches the drift immediately.

  describe "canonical forms (every entry in FAREWELLS, exact)" do
    Pito::Chat::Parser::FAREWELLS.each do |phrase|
      it "recognizes #{phrase.inspect}" do
        expect(farewell?(phrase)).to be(true)
      end
    end
  end

  # ── 2. Case normalization — downcased before comparison ─────────────────────

  describe "case normalization (input downcased before matching)" do
    {
      # single-word
      "BYE"             => "bye",
      "BYEBYE"          => "byebye",
      "GOODBYE"         => "goodbye",
      "CYA"             => "cya",
      "SEEYA"           => "seeya",
      "LATER"           => "later",
      "LATERS"          => "laters",
      "TTYL"            => "ttyl",
      "CIAO"            => "ciao",
      "ADIOS"           => "adios",
      "PEACE"           => "peace",
      "FAREWELL"        => "farewell",
      "GOODNIGHT"       => "goodnight",
      "GN"              => "gn",
      "TOODLES"         => "toodles",
      # mixed-case single-word
      "Bye"             => "bye",
      "Goodbye"         => "goodbye",
      "Farewell"        => "farewell",
      "Toodles"         => "toodles",
      # multi-word
      "Bye Bye"         => "bye bye",
      "Good Bye"        => "good bye",
      "See Ya"          => "see ya",
      "SEE YOU"         => "see you",
      "See You"         => "see you",
      "See'Ya"          => "see'ya",       # apostrophe preserved (not trailing)
      "See You Later"   => "see you later",
      "See Ya Later"    => "see ya later",
      "Talk Later"      => "talk later",
      "ADIÓS"           => "adiós",        # Unicode downcasing
      "Adiós"           => "adiós",
      "Hasta Luego"     => "hasta luego",
      "HASTA LUEGO"     => "hasta luego",
      "Hasta La Vista"  => "hasta la vista",
      "HASTA LA VISTA"  => "hasta la vista",
      "Peace Out"       => "peace out",
      "PEACE OUT"       => "peace out",
      "Good Night"      => "good night",
      "GOOD NIGHT"      => "good night",
      "Take Care"       => "take care",
      "TAKE CARE"       => "take care"
    }.each do |input, canonical|
      it "#{input.inspect} → normalized #{canonical.inspect} → farewell" do
        expect(farewell?(input)).to be(true)
      end
    end
  end

  # ── 3. Trailing punctuation stripped ────────────────────────────────────────
  #
  # gsub(/[[:punct:]]+\z/, "") removes one or more trailing ASCII punctuation
  # characters (!"#%&'()*+,-./:;<=>?@[\]^_`{|}~) before the set lookup.

  describe "trailing punctuation stripped (single and sequences)" do
    {
      # single punct
      "bye!"            => "bye",
      "bye."            => "bye",
      "bye,"            => "bye",
      "bye?"            => "bye",
      "goodbye."        => "goodbye",
      "good bye."       => "good bye",
      "cya!"            => "cya",
      "see ya!"         => "see ya",
      "see you!"        => "see you",
      "later!"          => "later",
      "laters."         => "laters",
      "ttyl!"           => "ttyl",
      "talk later!"     => "talk later",
      "ciao!"           => "ciao",
      "adios!"          => "adios",
      "hasta luego!"    => "hasta luego",
      "hasta la vista!" => "hasta la vista",
      "peace!"          => "peace",
      "peace out!"      => "peace out",
      "farewell!"       => "farewell",
      "good night!"     => "good night",
      "goodnight!"      => "goodnight",
      "gn!"             => "gn",
      "take care!"      => "take care",
      "toodles!"        => "toodles",
      "seeya!"          => "seeya",
      "byebye!"         => "byebye",
      "bye bye!"        => "bye bye",
      "see you later!"  => "see you later",
      "see ya later!"   => "see ya later",
      # punctuation sequences
      "bye!!"           => "bye",
      "bye..."          => "bye",
      "bye?!"           => "bye",
      "bye!?!"          => "bye",
      "goodbye..."      => "goodbye",
      "later!!"         => "later",
      "ciao..."         => "ciao",
      "peace!!"         => "peace",
      "farewell..."     => "farewell",
      "good night..."   => "good night"
    }.each do |input, canonical|
      it "#{input.inspect} → trailing punct stripped to #{canonical.inspect} → farewell" do
        expect(farewell?(input)).to be(true)
      end
    end
  end

  # ── 4. Leading/trailing whitespace stripped ──────────────────────────────────

  describe "leading/trailing whitespace stripped" do
    {
      "  bye"             => "bye",
      "bye  "             => "bye",
      "  bye  "           => "bye",
      "  goodbye  "       => "goodbye",
      "  good bye  "      => "good bye",
      "  cya  "           => "cya",
      "  see ya  "        => "see ya",
      "  see you  "       => "see you",
      "  later  "         => "later",
      "  ttyl  "          => "ttyl",
      "  ciao  "          => "ciao",
      "  farewell  "      => "farewell",
      "  good night  "    => "good night",
      "  gn  "            => "gn",
      "  toodles  "       => "toodles",
      "  hasta luego  "   => "hasta luego",
      "  peace out  "     => "peace out",
      "  take care  "     => "take care",
      "\tbye\t"           => "bye",           # tab whitespace
      "\n bye \n"         => "bye"            # newline whitespace
    }.each do |input, canonical|
      it "#{input.inspect} → whitespace stripped to #{canonical.inspect} → farewell" do
        expect(farewell?(input)).to be(true)
      end
    end
  end

  # ── 5. Internal whitespace collapsed (multiple spaces → single space) ────────

  describe "internal whitespace collapsed to single space" do
    {
      "good  bye"           => "good bye",
      "bye  bye"            => "bye bye",
      "see   ya"            => "see ya",
      "see  you"            => "see you",
      "see  you  later"     => "see you later",
      "see  ya  later"      => "see ya later",
      "good  night"         => "good night",
      "peace  out"          => "peace out",
      "hasta  luego"        => "hasta luego",
      "hasta  la  vista"    => "hasta la vista",
      "take  care"          => "take care",
      "talk  later"         => "talk later"
    }.each do |input, canonical|
      it "#{input.inspect} → whitespace-collapsed to #{canonical.inspect} → farewell" do
        expect(farewell?(input)).to be(true)
      end
    end
  end

  # ── 6. Combined variants (case + punctuation + whitespace together) ──────────

  describe "combined normalization variants" do
    {
      "  BYE!  "            => "bye",
      "GOODBYE!"            => "goodbye",
      "  Good Bye!  "       => "good bye",
      "Good  Bye!"          => "good bye",
      "SEE YA!"             => "see ya",
      "  See  Ya!  "        => "see ya",
      "See You!"            => "see you",
      "LATER!"              => "later",
      "  LATER!  "          => "later",
      "TTYL!"               => "ttyl",
      "  TTYL!  "           => "ttyl",
      "Ciao!"               => "ciao",
      "Adios!"              => "adios",
      "ADIÓS!"              => "adiós",
      "  ADIÓS!  "          => "adiós",
      "Hasta Luego!"        => "hasta luego",
      "  Hasta  Luego!  "   => "hasta luego",
      "HASTA LA VISTA!"     => "hasta la vista",
      "  Hasta  La  Vista." => "hasta la vista",
      "PEACE OUT!"          => "peace out",
      "Good Night!"         => "good night",
      "  GOOD  NIGHT!  "    => "good night",
      "GN!"                 => "gn",
      "  GN!  "             => "gn",
      "Take Care!"          => "take care",
      "  Take  Care!  "     => "take care",
      "TOODLES!"            => "toodles",
      "  FAREWELL!  "       => "farewell",
      "FAREWELL..."         => "farewell",
      "See You Later!"      => "see you later",
      "SEE YOU LATER!!"     => "see you later",
      "Bye Bye!"            => "bye bye",
      "  BYE  BYE!  "       => "bye bye",
      "SEE'YA!"             => "see'ya"   # apostrophe in middle, NOT trailing punct
    }.each do |input, canonical|
      it "#{input.inspect} → #{canonical.inspect} → farewell" do
        expect(farewell?(input)).to be(true)
      end
    end
  end

  # ── 7. Negative — must NOT be recognized as farewell ────────────────────────
  #
  # Phrases that look farewell-adjacent but differ from every entry in FAREWELLS
  # after normalization.  These should produce :greet, a known-verb, or :unknown,
  # but never :farewell.

  describe "not recognized as farewell" do
    {
      # greetings
      "hi"                    => "greeting",
      "hello"                 => "greeting",
      "hey"                   => "greeting",
      "good morning"          => "greeting",
      "good evening"          => "greeting",
      "hola"                  => "greeting",
      # extra word appended — falls outside the set
      "later today"           => "later + extra word",
      "bye bye bye"           => "three byes, not two",
      "see you soon"          => "not in set",
      "see you around"        => "not in set",
      "good night everyone"   => "extra word",
      "peace man"             => "extra word",
      "see ya tomorrow"       => "extra word",
      "take care now"         => "extra word",
      "hasta la vista baby"   => "extra word",
      # NOTE: "farewell my friend" omitted — "farewell" is ALSO a registered
      # grammar-spec token (:farewell chat spec) so the verb-token path fires
      # for "farewell <anything>" and returns verb: :farewell as well.  Not a
      # bug to fix here; noted for source-comment/behaviour inconsistency.
      # common typos / abbreviations not in FAREWELLS
      "byee"                  => "double-e typo",
      "bya"                   => "typo",
      "l8r"                   => "leet abbreviation",
      "ttfn"                  => "abbreviation not in set",
      "cu"                    => "abbreviation not in set",
      "cu later"              => "not in set",
      "tc"                    => "abbreviation not in set",
      "cyu"                   => "not in set",
      "bb"                    => "not in set",
      # known chat verbs — must not be mistaken for farewell
      "list"                  => "known chat verb",
      "help"                  => "known chat verb",
      "analyze"               => "known chat verb",
      "sync"                  => "known chat verb",
      # empty input
      ""                      => "empty string",
      # phrase with interior non-farewell content
      "i'll talk to you later" => "sentence, not in set",
      "have a good day"       => "not in set",
      "good day"              => "not in set"
    }.each do |input, reason|
      it "#{input.inspect} is NOT a farewell (#{reason})" do
        expect(farewell?(input)).to be(false)
      end
    end
  end
end
