# Phase 9 — Login-with-Google Drop + GoogleIdentity → YoutubeConnection
# rename (ADR 0006). Per the architect spec at
# `docs/plans/beta/09-login-with-google-drop/specs/01-google-identity-rename.md`.
#
# The model's role narrowed to "an OAuth grant that gives pito access to
# one or more YouTube channels." The current name encodes the dual role
# (user-identity AND API grant) that ADR 0006 retires. Rename the table,
# every FK column, and every related index so the schema reflects the
# narrowed scope.
#
# Migration shape (locked decision in the spec): `rename_table` +
# `rename_column`. Active Record Encryption metadata is keyed by attribute
# name on the model, NOT by table name, so the encrypted `access_token`
# and `refresh_token` columns survive the rename trivially.
#
# Rollback is explicitly NOT supported. Per ADR 0003 (inherited from
# Phase 8) the canonical reset path is `bin/rails db:drop db:create
# db:migrate db:seed`. The `down` method below is bookkeeping only.
class RenameGoogleIdentityToYoutubeConnection < ActiveRecord::Migration[8.1]
  def up
    # 1. Rename the table itself.
    rename_table :google_identities, :youtube_connections

    # 2. Rename FK columns on dependent tables.
    rename_column :channels, :oauth_identity_id, :youtube_connection_id
    rename_column :videos, :oauth_identity_id, :youtube_connection_id
    rename_column :youtube_api_calls, :google_identity_id, :youtube_connection_id

    # 3. Rename indexes that Postgres did not auto-rename (Postgres
    # auto-renames the index when its underlying column or table is
    # renamed only when the index name was generated by Rails' default
    # convention; explicit names need explicit rename calls).
    rename_index_if_exists "youtube_connections",
      "index_google_identities_on_user_id",
      "index_youtube_connections_on_user_id"
    rename_index_if_exists "youtube_connections",
      "index_google_identities_on_google_subject_id",
      "index_youtube_connections_on_google_subject_id"

    rename_index_if_exists "channels",
      "index_channels_on_oauth_identity_id",
      "index_channels_on_youtube_connection_id"

    rename_index_if_exists "videos",
      "index_videos_on_oauth_identity_id",
      "index_videos_on_youtube_connection_id"

    rename_index_if_exists "youtube_api_calls",
      "index_youtube_api_calls_on_google_identity_id",
      "index_youtube_api_calls_on_youtube_connection_id"
    rename_index_if_exists "youtube_api_calls",
      "index_youtube_api_calls_on_identity_time",
      "index_youtube_api_calls_on_connection_time"
  end

  def down
    rename_index_if_exists "youtube_api_calls",
      "index_youtube_api_calls_on_connection_time",
      "index_youtube_api_calls_on_identity_time"
    rename_index_if_exists "youtube_api_calls",
      "index_youtube_api_calls_on_youtube_connection_id",
      "index_youtube_api_calls_on_google_identity_id"

    rename_index_if_exists "videos",
      "index_videos_on_youtube_connection_id",
      "index_videos_on_oauth_identity_id"

    rename_index_if_exists "channels",
      "index_channels_on_youtube_connection_id",
      "index_channels_on_oauth_identity_id"

    rename_index_if_exists "youtube_connections",
      "index_youtube_connections_on_google_subject_id",
      "index_google_identities_on_google_subject_id"
    rename_index_if_exists "youtube_connections",
      "index_youtube_connections_on_user_id",
      "index_google_identities_on_user_id"

    rename_column :youtube_api_calls, :youtube_connection_id, :google_identity_id
    rename_column :videos, :youtube_connection_id, :oauth_identity_id
    rename_column :channels, :youtube_connection_id, :oauth_identity_id

    rename_table :youtube_connections, :google_identities
  end

  private

  # Postgres tracks indexes by name (not by attached table), so a
  # rename_table / rename_column does NOT propagate to the index name
  # automatically when the index was created with an explicit `name:`.
  # Skip if the index has already been renamed — the migration becomes
  # idempotent against a partially-applied state.
  def rename_index_if_exists(table, old_name, new_name)
    return unless index_name_exists?(table, old_name)

    rename_index table, old_name, new_name
  end
end
