module Pito
  module Transitions
    # Pito::Transitions::Exporter — writes the canonical token block into the
    # CSS theme file (sentinel-wrapped, idempotent).
    #
    # Driven by `rake pito:transitions:export`. Re-running produces byte-
    # identical output.
    module Exporter
      module_function

      CSS_PATH  = Rails.root.join("tmp/_theme.css")

      SENTINEL_OPEN  = "/* >>> TRANSITIONS_TOKENS auto-generated by rake pito:transitions:export — DO NOT EDIT <<< */"
      SENTINEL_CLOSE = "/* <<< TRANSITIONS_TOKENS <<< */"

      def export_css!
        write_or_replace(CSS_PATH, render_css_block)
      end

      def render_css_block
        lines = [ SENTINEL_OPEN, ":root {" ]
        Tokens::ALL.each do |key, value|
          css_name = "--tui-trn-#{key.to_s.tr('_', '-')}"
          css_value = format_css_value(key, value)
          lines << "  #{css_name}: #{css_value};"
        end
        lines << "}"
        lines << SENTINEL_CLOSE
        lines.join("\n") + "\n"
      end

      def format_css_value(key, value)
        case value
        when Numeric
          key.to_s.end_with?("_ms") ? "#{value}ms" : value.to_s
        else
          value.to_s
        end
      end

      def write_or_replace(path, block)
        content = path.exist? ? path.read : ""
        if content.include?(SENTINEL_OPEN) && content.include?(SENTINEL_CLOSE)
          new_content = content.sub(/#{Regexp.escape(SENTINEL_OPEN)}.*?#{Regexp.escape(SENTINEL_CLOSE)}\n?/m, block)
          path.write(new_content)
        else
          path.write(content + "\n" + block)
        end
      end
    end
  end
end
