module Pito
  module Transitions
    # Pito::Transitions::Exporter — writes the canonical token block into the
    # CSS theme file (sentinel-wrapped, idempotent) and writes the whole Rust
    # transitions file (whole-file generated, no hand-edits preserved).
    #
    # Driven by `rake pito:transitions:export`. Re-running produces byte-
    # identical output.
    module Exporter
      module_function

      CSS_PATH  = Rails.root.join("tmp/_theme.css")
      RUST_PATH = Rails.root.join("extras/cli/src/transitions.rs")

      SENTINEL_OPEN  = "/* >>> TRANSITIONS_TOKENS auto-generated by rake pito:transitions:export — DO NOT EDIT <<< */"
      SENTINEL_CLOSE = "/* <<< TRANSITIONS_TOKENS <<< */"

      def export_css!
        write_or_replace(CSS_PATH, render_css_block)
      end

      def export_rust!
        RUST_PATH.write(render_rust_block)
      end

      def render_css_block
        lines = [ SENTINEL_OPEN, ":root {" ]
        Tokens::ALL.each do |key, value|
          css_name = "--tui-trn-#{key.to_s.tr('_', '-')}"
          css_value = format_css_value(key, value)
          lines << "  #{css_name}: #{css_value};"
        end
        lines << "}"
        lines << SENTINEL_CLOSE
        lines.join("\n") + "\n"
      end

      def render_rust_block
        body = [
          "// >>> TRANSITIONS_TOKENS auto-generated by rake pito:transitions:export — DO NOT EDIT <<<",
          "// Pito::Transitions::Tokens parity for the Ratatui TUI.",
          "//",
          "// 2 transitions (scramble-settle + color-crossfade) + 1 decoration (shimmer).",
          "// All values mirror app/services/pito/transitions/tokens.rb.",
          ""
        ]
        Tokens::ALL.each do |key, value|
          rust_name = key.to_s.upcase
          rust_value, rust_type = format_rust_value(value)
          body << "pub const #{rust_name}: #{rust_type} = #{rust_value};"
        end
        body << ""
        body.join("\n") + "\n"
      end

      def format_css_value(key, value)
        case value
        when Numeric
          key.to_s.end_with?("_ms") ? "#{value}ms" : value.to_s
        else
          value.to_s
        end
      end

      def format_rust_value(value)
        case value
        when Integer then [ value.to_s, "u32" ]
        when String  then [ "\"#{value}\"", "&'static str" ]
        else              [ value.to_s, "&'static str" ]
        end
      end

      def write_or_replace(path, block)
        content = path.exist? ? path.read : ""
        if content.include?(SENTINEL_OPEN) && content.include?(SENTINEL_CLOSE)
          new_content = content.sub(/#{Regexp.escape(SENTINEL_OPEN)}.*?#{Regexp.escape(SENTINEL_CLOSE)}\n?/m, block)
          path.write(new_content)
        else
          path.write(content + "\n" + block)
        end
      end
    end
  end
end
