# frozen_string_literal: true

module Pito
  # Follow-up engine — opt-in mechanism for messages that accept a follow-up reply.
  #
  # == Payload contract
  #
  # Any event that is "follow-up-able" carries three keys in its payload:
  #
  #   reply_handle   (String)  — unique hashtag, e.g. "delta-4823".
  #                              Generated by Pito::HandleGenerator.call(conversation).
  #                              Reserved for the lifetime of the conversation —
  #                              even after the message is consumed the handle is NOT
  #                              recycled.
  #   reply_target   (String)  — handler id registered in Pito::FollowUp::Registry,
  #                              e.g. "theme_list" or "confirmation".
  #   reply_consumed (Boolean) — optional.  When true: the affordance is hidden and
  #                              the event is no longer routable.  The handle remains
  #                              reserved.  Omitted / false = still open.
  #
  # == Stamping
  #
  #   Pito::FollowUp.make_followupable!(payload, target: "theme_list", conversation: conv)
  #
  # Injects `reply_handle` and `reply_target` into *payload* (Hash, string or symbol
  # keys — always written as string keys).  Idempotent: a payload that already has
  # `reply_handle` is returned unchanged.
  #
  # == Predicates
  #
  #   Pito::FollowUp.followupable?(payload)  → true when reply_handle is present
  #   Pito::FollowUp.consumed?(payload)      → true when reply_consumed is truthy
  module FollowUp
    module_function

    # Stamp *payload* with follow-up fields.  Returns the mutated payload.
    # Idempotent: a payload already carrying `reply_handle` is returned as-is.
    #
    # @param payload       [Hash]   mutable payload hash (string or symbol keys).
    # @param target:       [String] handler id (must be registered in Registry before use).
    # @param conversation: [Conversation] used to generate a unique handle.
    # @return              [Hash]   the same hash, with reply_handle + reply_target injected.
    def make_followupable!(payload, target:, conversation:)
      return payload if payload["reply_handle"].present? || payload[:reply_handle].present?

      handle = Pito::HandleGenerator.call(conversation)
      payload["reply_handle"] = handle
      payload["reply_target"] = target.to_s
      payload
    end

    # Returns true when the payload has a `reply_handle` (i.e. is follow-up-able).
    def followupable?(payload)
      payload["reply_handle"].present? || payload[:reply_handle].present?
    end

    # Returns true when `reply_consumed` is explicitly true.
    def consumed?(payload)
      v = payload["reply_consumed"] || payload[:reply_consumed]
      v == true || v == "true"
    end
  end
end
