# frozen_string_literal: true

require_relative "registry"

module Pito
  module Themes
    # Generates a CSS string containing:
    #
    #   1. A `:root { … }` block with the default theme tokens (tokyo-night),
    #      so pages without an explicit `data-theme` attribute render correctly.
    #
    #   2. One `[data-theme="<slug>"] { … }` block for every theme registered
    #      in Registry.all.
    #
    # Token-key → CSS-variable mapping
    # ---------------------------------
    #   bg_root        → --bg-root
    #   bg_surface     → --bg-surface
    #   bg_elevated    → --bg-elevated
    #   border_default → --border-default
    #   border_faded   → --border-faded
    #   fg_default     → --fg-default
    #   fg_dim         → --fg-dim
    #   fg_faded       → --fg-faded
    #   accent_*       → --accent-*   (underscore → hyphen)
    #   brand_pito     → --brand-pito
    #
    # Usage
    # -----
    #   css = Pito::Themes::CssGenerator.call
    #   File.write("app/assets/tailwind/themes.css", css)
    #
    # The file is also written by the `pito:themes:export` rake task.
    module CssGenerator
      HEADER = "/* GENERATED by rake pito:themes:export — do not edit */\n"

      # @return [String] complete CSS string
      def self.call
        default_def = Registry.default
        all_defs    = Registry.all

        lines = [ HEADER, "" ]

        lines << ":root {"
        default_def.tokens.each { |k, v| lines << "  #{css_var(k)}: #{v};" }
        lines << "}"
        lines << ""

        all_defs.each do |defn|
          lines << "[data-theme=\"#{defn.slug}\"] {"
          defn.tokens.each { |k, v| lines << "  #{css_var(k)}: #{v};" }
          lines << "}"
          lines << ""
        end

        lines.join("\n")
      end

      # Maps a token Symbol key to its CSS custom-property name.
      # e.g. :bg_root → "--bg-root", :accent_purple → "--accent-purple"
      #
      # @param key [Symbol]
      # @return [String]
      def self.css_var(key)
        "--#{key.to_s.tr("_", "-")}"
      end
      private_class_method :css_var
    end
  end
end
