# Pito::BackupCodeInputComponent — 8-box segmented input for a backup auth code.
#
# Purpose:
#   Mirrors TotpCodeInputComponent but targets the 8-character alphanumeric
#   backup codes generated by `pito:auth:enroll`
#   (`SecureRandom.alphanumeric(8).downcase`). The visual pattern is identical —
#   one discrete input box per character — so the user sees a familiar segmented
#   row regardless of whether they're entering a TOTP code or a backup code.
#
# Markup contract:
#   - 8 visible `<input type="text">` boxes with `inputmode="text"`,
#     `maxlength="1"`, and `data-backup-code-input-target="char"`.
#   - Boxes accept any alphanumeric character (a-z 0-9); non-alphanumeric
#     keystrokes are stripped by the Stimulus controller.
#   - The FIRST box carries `autocomplete="one-time-code"` so password managers
#     can fill from a saved backup code string.
#   - A hidden `<input name="<field>">` carries the concatenated 8-char value
#     on form submit.
#   - The container element carries `data-controller="backup-code-input"`.
#
# Stimulus controller: `backup-code-input` (app/javascript/controllers/backup_code_input_controller.js)
#   Handles: input validation (alphanumeric only), auto-advance, backspace-step,
#   ArrowLeft/Right, paste distribution from any cell, hidden-field sync.
#   Does NOT auto-submit — backup codes require the user to press [log in].
#
# CSS: shares `.totp-modal-boxes` / `.totp-modal-box` sizing rules
#   (declared with the TotpCodeInputComponent). Width naturally stretches
#   to accommodate 8 boxes inside the 360px dialog.
#
# kwargs:
#   @param field [Symbol, String] form-param name on the hidden aggregation field.
#     Defaults to `:backup_code` since SessionsController#create reads that param.
#   @param autofocus [Boolean] whether the first box gets autofocus. Defaults false
#     because this component is initially hidden; the pito-auth-dialog Stimulus
#     controller sets focus when toggling into backup mode.
#
# Related:
#   - TotpCodeInputComponent — 6-digit numeric sibling
#   - app/javascript/controllers/backup_code_input_controller.js
#   - Pito::AuthDialogComponent (consumer)
module Pito
  class BackupCodeInputComponent < ViewComponent::Base
    def initialize(field: :backup_code, autofocus: false)
      @field    = field.to_s
      @autofocus = autofocus
    end

    attr_reader :field

    def autofocus?
      @autofocus
    end
  end
end
